### ISSUE TITLE
配置完Token后，DC中机器人未在线，输入消息也没有反应

### ISSUE THREAD

**Issue by Walkersifolia** [TimeRainStarSky/Yunzai-Discord-Plugin#2]
![image](https://github.com/TimeRainStarSky/Yunzai-Discord-Plugin/assets/129571444/2daa7f6d-5d86-43a6-ad50-036bef0ec753)
![image](https://github.com/TimeRainStarSky/Yunzai-Discord-Plugin/assets/129571444/d4ff8740-6ea8-4003-866f-3703c0e0178c)

**Comment by geol** [comment]
请问你代理怎么处理的（云崽的代理）？我看作者写得有一点点简单，我不是很明白。

**Comment by Walkersifolia** [comment]
> 请问你代理怎么处理的（云崽的代理）？我看作者写得有一点点简单，我不是很明白。

没处理，因为我服务器在国外

**Comment by geol** [comment]
现在我的服务器已经挂了梯子……我现在有个疑问，是不是trss yunzai是必须先登陆qq然后再输入“#安装Discord-Plugin”，然后才能使用dc机器人？qq老是被封，这次竟然封到大号头上，准备跑路了。

**Comment by Walkersifolia** [comment]
> 现在我的服务器已经挂了梯子……我现在有个疑问，是不是trss yunzai是必须先登陆qq然后再输入“#安装Discord-Plugin”，然后才能使用dc机器人？qq老是被封，这次竟然封到大号头上，准备跑路了。

控制台也可以直接输入#指令

**Comment by geol** [comment]
> > 现在我的服务器已经挂了梯子……我现在有个疑问，是不是trss yunzai是必须先登陆qq然后再输入“#安装Discord-Plugin”，然后才能使用dc机器人？qq老是被封，这次竟然封到大号头上，准备跑路了。
> 
> 
> 
> 控制台也可以直接输入#指令

耐撕！顺便问一哈，你提的issue现在还没解决吗？
