### ISSUE TITLE
在discord中发送指令，无反馈图片，在控制台中输入有反馈，无错误

### ISSUE THREAD

**Issue by ghost** [TimeRainStarSky/Yunzai-Discord-Plugin#5]
![image](https://github.com/TimeRainStarSky/Yunzai-Discord-Plugin/assets/148192561/245dcb64-2efa-43a9-8ffe-f7216334ca6c)
![image](https://github.com/TimeRainStarSky/Yunzai-Discord-Plugin/assets/148192561/1f812773-e597-410c-aa5f-919eadf85cc9)
![image](https://github.com/TimeRainStarSky/Yunzai-Discord-Plugin/assets/148192561/61751a2e-0f92-4b2f-8b69-1612e9d991fb)

**Comment by TimeRainStarSky** [comment]
#全部更新
